### ISSUE TITLE
Failed to build due to FLAC.

### ISSUE THREAD

**Issue by aperomsik** [PaulWoitaschek/MaterialAudiobookPlayer#594]
Tried updating my build to current master but I can't build with Android Studio 2.3.2. Is it supposed to work with that version?

Took some time to find what it was complaining about but eventually I found this:

```
In file included from /home/aaron/work/bplayer/exoplayer-flac/src/main/jni/flac_parser.cc:17:
/home/aaron/work/bplayer/exoplayer-flac/src/main/jni/include/flac_parser.h:23:10: fatal error: 
      'FLAC/stream_decoder.h' file not found
#include "FLAC/stream_decoder.h"
```

Seems maybe flac download failed... any suggestions for figuring out why? I am building on Ubuntu 17.04 .

**Comment by PaulWoitaschek** [comment]
Is the directory `exoplayer-flac/src/main/jni/flac` present and not empty?

Try deleting the `exoplayer-flac/src/main/jni/flac` folder and try again.
Does  it build from command line?

**Comment by aperomsik** [comment]
Directory did not exist. 

Not sure about command line, so I tried "/usr/local/android-studio/gradle/gradle-3.2/bin/gradle build" and it complained that I needed at least 3.3 .

So then I tried " ~/.gradle/wrapper/dists/gradle-3.5-all/exhrs6ca08n232b14ue48lbye/gradle-3.5/bin/gradle build" and it did download and build flac. The rest is still building but I guess it will work.

**Comment by PaulWoitaschek** [comment]
Always use the local distribution of gradle as it will lead to reproducible builds. 

![screen](https://cloud.githubusercontent.com/assets/743462/26555404/265c8562-4495-11e7-98e9-9422ed7b226f.png)

Or from command line `./gradlew ...` instead of `gradle ...`

**Comment by PaulWoitaschek** [comment]
Btw in this case the app makes use of the buildSrc folder that (i believe) was introduced in Gradle 3.5

**Comment by aperomsik** [comment]
You said "local" but your screenshot has "default" checked. And so does mine. I didn't change it. 

Although I didn't know which gradle to run, I assume Android Studio does. To be sure, I reset to an older commit, cleaned out everything related to exoplayer-flac and exoplayer-opus, reset back to current master, rebooted, and started Android Studio again. I could see gradle 3.5 running, but I still got the same error.

I should be OK as long as I run gradlew from the command line once, but it would be nice if a fresh clone could build in AS.

**Comment by aperomsik** [comment]
Now I am getting this error instead, both in AS and at the command line:

```
Execution failed for task ':audiobook:validateSigningOpensourceRelease'.
> Keystore file not set for signing config release
```

AS shows BuildVariant set to opensourceDebug. I used to get something like this if I tried to build release, but debug builds were OK without a keystore. Is it an intentional change?

**Comment by PaulWoitaschek** [comment]
So the issue is resolved for you?

**Comment by vituocgia** [comment]
Hello there, I cannot compile the project by using latest Gradle and Android studio :(
I'm using windows 10, is there any advice :(

> PREDEX ENABLED
signing.properties not found
The setTestClassesDir(File) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the setTestClassesDirs(FileCollection) method instead.
The getTestClassesDir() method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the getTestClassesDirs() method instead.
The ConfigurableReport.setDestination(Object) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the method ConfigurableReport.setDestination(File) instead.
Gradle now uses separate output directories for each JVM language, but this build assumes a single directory for all classes from a source set. This behaviour has been deprecated and is scheduled to be removed in Gradle 5.0
	at build_czcakafsazjxy2aqzfn5k9cjl$_run_closure2$_closure3.doCall(D:\Android_Apps\AudioBook\chapterreader\build.gradle:19)
process_begin: CreateProcess(NULL, "", ...) failed.
make: *** No rule to make target `D:/Android_Apps/AudioBook/exoplayer-flac/src/main/jni/flac/src/libFLAC/bitmath.c', needed by `D:/Android_Apps/AudioBook/exoplayer-flac/build/intermediates/ndkBuild/debug/obj/local/armeabi/objs/flacJNI/flac/src/libFLAC/bitmath.o'.  Stop.
process_begin: CreateProcess(NULL, "", ...) failed.
make: *** No rule to make target `D:/Android_Apps/AudioBook/exoplayer-flac/src/main/jni/flac/src/libFLAC/bitmath.c', needed by `D:/Android_Apps/AudioBook/exoplayer-flac/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/objs/flacJNI/flac/src/libFLAC/bitmath.o'.  Stop.
process_begin: CreateProcess(NULL, "", ...) failed.
make: *** No rule to make target `D:/Android_Apps/AudioBook/exoplayer-flac/src/main/jni/flac/src/libFLAC/bitmath.c', needed by `D:/Android_Apps/AudioBook/exoplayer-flac/build/intermediates/ndkBuild/debug/obj/local/arm64-v8a/objs/flacJNI/flac/src/libFLAC/bitmath.o'.  Stop.
process_begin: CreateProcess(NULL, "", ...) failed.
make: *** No rule to make target `D:/Android_Apps/AudioBook/exoplayer-flac/src/main/jni/flac/src/libFLAC/bitmath.c', needed by `D:/Android_Apps/AudioBook/exoplayer-flac/build/intermediates/ndkBuild/debug/obj/local/x86/objs/flacJNI/flac/src/libFLAC/bitmath.o'.  Stop.
process_begin: CreateProcess(NULL, "", ...) failed.
make: *** No rule to make target `D:/Android_Apps/AudioBook/exoplayer-flac/src/main/jni/flac/src/libFLAC/bitmath.c', needed by `D:/Android_Apps/AudioBook/exoplayer-flac/build/intermediates/ndkBuild/debug/obj/local/x86_64/objs/flacJNI/flac/src/libFLAC/bitmath.o'.  Stop.
process_begin: CreateProcess(NULL, "", ...) failed.
make: *** No rule to make target `D:/Android_Apps/AudioBook/exoplayer-flac/src/main/jni/flac/src/libFLAC/bitmath.c', needed by `D:/Android_Apps/AudioBook/exoplayer-flac/build/intermediates/ndkBuild/debug/obj/local/mips/objs/flacJNI/flac/src/libFLAC/bitmath.o'.  Stop.
process_begin: CreateProcess(NULL, "", ...) failed.
make: *** No rule to make target `D:/Android_Apps/AudioBook/exoplayer-flac/src/main/jni/flac/src/libFLAC/bitmath.c', needed by `D:/Android_Apps/AudioBook/exoplayer-flac/build/intermediates/ndkBuild/debug/obj/local/mips64/objs/flacJNI/flac/src/libFLAC/bitmath.o'.  Stop.
app: 'androidProcessor' dependencies won't be recognized as kapt annotation processors. Please change the configuration name to 'kapt' for these artifacts: 'com.android.databinding:compiler:2.3.3'.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_proprietaryDebugApk'.
   > A problem occurred configuring project ':exoplayer-flac'.
      > executing external native build for ndkBuild D:\Android_Apps\AudioBook\exoplayer-flac\src\main\jni\Android.mk

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

**Comment by PaulWoitaschek** [comment]
Did you check https://github.com/PaulWoitaschek/Voice#building-the-project-on-windows ?

**Comment by LawrenceWence** [comment]
I have exactly the same problem as @vituocgia.
So far I had no success to work around it. If you run everything with debug logs you get the hint that it is related to some problems with the ndk-build.

I see:
[LIFECYCLE] [org.gradle.api.Project] make: *** No rule to make target ....flac/src/main/jni/flac/src/libFLAC/bitmath.c', needed by ......Voice/exoplayer-flac/build/intermediates/ndkBuild/debug/obj/local/mips64/objs/flacJNI/flac/src/libFLAC/bitmath.o'.  Stop.

I get exactly the same error message if I run ndk-build from commandline. I use version 15.2.4203891 of the NDK, maybe one of the last versions has broken something.
